- name: Install Zsh
  package:
    name: zsh
    state: latest

- name: Create .zsh directory for plugins
  file:
    path: "/home/{{ username }}/.zsh"
    state: directory
    mode: "0755"
    owner: '{{ username }}'
    group: '{{ username }}'

- name: Clone the zshrc repository
  git:
    repo: "{{ zshrc_repo }}"
    dest: "/home/{{ username }}/.zsh/zshrc"
    force: yes
  become_user: '{{ username }}'

- name: Swap out the zshrc file
  copy:
    src: "/home/{{ username }}/.zsh/zshrc/.zshrc"
    dest: /home/{{ username }}/.zshrc
    remote_src: yes
    owner: '{{ username }}'
    group: '{{ username }}'
  become_user: '{{ username }}'

- name: Clone zsh plugins
  git:
    repo: "{{ item }}"
    dest: "/home/{{ username }}/.zsh/{{ item | basename | splitext | first }}"
    clone: yes
    update: yes
  become_user: '{{ username }}'
  loop: "{{ zsh_plugins }}"

- name: Set zsh as default shell for {{ username }}
  user:
    name: '{{ username }}'
    shell: /bin/zsh