- name: Update packages
  apt: 
    update_cache: yes
    upgrade: yes

- name: Install essential packages
  package: 
    name: "{{ packages }}"
    state: latest

- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for '{{ username }}'
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Restart SSH service
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed

- name: Generate SSH key pair for Git
  community.crypto.openssh_keypair:
    path: "/home/{{ username }}/.ssh/id_ed25519"
    type: ed25519
    comment: "{{ ansible_user }}@{{ ansible_hostname }}"
    state: present
    owner: '{{ username }}'
    group: '{{ username }}'

- name: Display SSH public key
  ansible.builtin.shell: cat "/home/{{ username }}/.ssh/id_ed25519.pub"
  register: ssh_public_key

- name: Show the key
  ansible.builtin.debug:
    msg: "{{ ssh_public_key.stdout }}"